#experimental only .. using /app/config folder configured in desktop-deployment.yaml
########################################################################################
apiVersion: v1
kind: ConfigMap
metadata:
  name: clone-props
  namespace: default
data:
  props.version: master       # 1
  props.env: dev              # 2
---
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-mgmt
  template:
    metadata:
      labels:
        app: config-mgmt
    spec:
      containers:
      initContainers:
        - name: git-clone
          image: alpine/git:1.0.4
          command: ['/bin/sh', '-c']
          args: ['git clone --branch $(props.version) https://github.com/makcalif/config-properties.git && mv config-properties/auth-service/$(props.env)/* /config'] # 3
          volumeMounts:
            - name: config
              mountPath: /config
          envFrom:
            - configMapRef:
                name: clone-props
      volumes:
        - name: config
          emptyDir: {}