apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: helloweb
  annotations:
    kubernetes.io/ingress.global-static-ip-name: web-static-ip
  labels:
    app: hello
spec:
  backend:
    serviceName: echo-service
    servicePort: 80
